name: Todo App CI Jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: sqlite:///./testdb.db
      SECRET_KEY: 32c13e3b5174ece2db353d022bc78c68f1551dd5ba3d1c48ae43880fe01693ac
      ALGORITHM: HS256

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      
      - name: Run tests
        run: |
          poetry run pytest

      - name: Format checker
        run: |
          poetry run black --check .